### ISSUE TITLE
2.5 --> 2.6: backwards incompatible change in MalformedCSVError#new

### ISSUE THREAD

**Issue by Spakman** [ruby/csv#104]
In Ruby 2.5, `CSV::MalformedCSVError` simply inherited from `RuntimeError`. In 2.6, it defines its own `#new`, taking 2 arguments (as opposed to the single argument of `RuntimeError`).

Code explicitly raising new errors of this class outside of the CSV library implementation itself breaks since it doesn't include the second argument (a line number).

Is making the line number optional something you'd entertain?

**Comment by kou** [comment]
Could you show codes that creating `CSV::MalformedCSVError`?

**Comment by Mifrill** [comment]
@kou just this:
```
    def raise_malformed_csv_error
      raise CSV::MalformedCSVError
    end
```
with 2.6 ruby it's raised this:
```
     Failure/Error: raise CSV::MalformedCSVError
     
     ArgumentError:
       wrong number of arguments (given 0, expected 2)
```
because of this:
```
  class MalformedCSVError < RuntimeError
    attr_reader :line_number
    alias_method :lineno, :line_number
    def initialize(message, line_number)
      @line_number = line_number
      super("#{message} in line #{line_number}.")
    end
  end
```

**Comment by kou** [comment]
Thanks.
One more question. Why do you want to raise `CSV::MalformedCSVError` manually?

**Comment by kou** [comment]
Thanks.
It seems that it's an application specific error and it's not a general CSV error. So you should use your own error class instead of reusing `CSV::MalformedCSVError`.

**Comment by Mifrill** [comment]
@kou  okay, thanks, I will take note and we will discuss it with colleagues. We've just got this error while ruby update. Now we'got how to resolve it. Thank you

**Comment by kou** [comment]
OK. I close this.
