### ISSUE TITLE
How to combine mode and options in CSV.foreach?

### ISSUE THREAD

**Issue by davideluque** [ruby/csv#113]
I am trying to iterate over a CSV that has a byte order mark (BOM) and headers.

```ruby
CSV.foreach('file.csv', "r:bom|utf-8") {}
```
Does the trick to address the byte order mark.

```ruby
CSV.foreach('file.csv', headers:true){}
```
Works to take the headers into consideration.

I can't find a way to combine both options.

--------
Ruby version: 2.4.2

**Comment by kou** [comment]
`CSV.foreach("file.csv", "r:bom|utf-8", headers: true) {}` will work.

**Comment by davideluque** [comment]
> `CSV.foreach("file.csv", "r:bom|utf-8", headers: true) {}` will work.

I tried your suggestion and I get an error

ArgumentError: wrong number of arguments (given 3, expected 1..2)
from /home/david/.rbenv/versions/2.4.2/lib/ruby/2.4.0/csv.rb:1145:in `foreach'

**Comment by kou** [comment]
`gem install csv` will work.

**Comment by davideluque** [comment]
> `gem install csv` will work.

Thanks, it does. Also `gem 'csv'` in gemfile.
