### ISSUE TITLE
csv 3.1.4 missing docs

### ISSUE THREAD

**Issue by joast** [ruby/csv#125]
gem install outputs:

> Couldn't find file to include '../doc/col_sep.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/row_sep.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/quote_char.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/field_size_limit.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/converters.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/unconverted_fields.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/headers.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/return_headers.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/header_converters.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/skip_blanks.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/skip_lines.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/liberal_parsing.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/nil_value.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/empty_value.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/col_sep.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/row_sep.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/quote_char.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/write_headers.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/force_quotes.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/quote_empty.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/write_converters.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/write_nil_value.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/write_empty_value.rdoc' from lib/csv.rb
> Couldn't find file to include '../doc/strip.rdoc' from lib/csv.rb
>

**Comment by topstone** [comment]
I got same outputs, that depend on #122 .

**Comment by kou** [comment]
Thanks for your report.
I've fixed and released a new version.

**Comment by joast** [comment]
Thank you!
