### ISSUE TITLE
Value with space inside triggers exception when strip enabled

### ISSUE THREAD

**Issue by Hugo-Hache** [ruby/csv#126]
With strip option enabled, a CSV with a value including a whitespace triggers the following exception `CSV::MalformedCSVError (TODO: Meaningful message in line 1.)`

Example : 

```
CSV.parse("a, bc ,d", strip: true).to_a # [["a", "bc", "d"]]
CSV.parse("a, b c ,d", strip: true).to_a # CSV::MalformedCSVError (TODO: Meaningful message in line 1.)
CSV.parse("a, b c ,d", strip: ' ').to_a # CSV::MalformedCSVError (TODO: Meaningful message in line 1.)
```

**Comment by kou** [comment]
Could you try the latest release?

**Comment by Hugo-Hache** [comment]
By manually installing the latest release (instead of the version packaged with Ruby 2.7.1) the issue is solved, thanks!
