### ISSUE TITLE
CSV::open mode defaults to "rb"

### ISSUE THREAD

**Issue by BurdetteLamar** [ruby/csv#132]
I'm continuing to look at the CSV doc, and am puzzled about ::open.

From the doc:

            open( filename, mode = "rb", **options ) { |faster_csv| ... }
            open( filename, **options ) { |faster_csv| ... }
            open( filename, mode = "rb", **options )
            open( filename, **options )

            This method opens an IO object, and wraps that with CSV. This is intended as the primary interface for writing a CSV file.

Primary interface for writing, but mode="rb"?

Am I missing something?

**Comment by kou** [comment]
I think that it wants to say "If you want to write a CSV with library, you will use `CSV.open(path, "wb") {|csv| csv << row}` in most cases".

Anyway, we can rewrite the description if we have more useful description for users.

**Comment by BurdetteLamar** [comment]
K, thanks.
