### ISSUE TITLE
MalformedCSVError when "BOM|UTF-8" on Windows

### ISSUE THREAD

**Issue by scivola** [ruby/csv#147]
MalformedCSVError may occur when encoding: "BOM|UTF-8" on Windows OS.

Reproduction code:

```rb
require "csv"

IO.binwrite "t.csv", ("a" * 100 + "\r\n") * 100
CSV.open("t.csv", encoding: "BOM|UTF-8").readlines
```

Result:

```
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/csv-3.1.5/lib/csv/parser.rb:920:in `parse_quotable_robust': Unquoted fields do not allow new line <"\\r"> in line 81. (CSV::MalformedCSVError)
```

Versions:
```
> ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]

> gem list csv

*** LOCAL GEMS ***
csv (3.1.5, default: 3.1.2)
```

Other conditions:

* It does not raise on macOS.
* It does not raise when not `"BOM|UTF-8"` but `"UTF-8"`
* It does not raise when the CSV has few lines (e.g. not 100 but 80 lines  in the above code)

**Comment by kou** [comment]
Thanks for your report.

It seems that this is a `IO#gets` problem. It converts some `\r\n` to `\n` with `universal_newline: false`. Could you report this to https://bugs.ruby-lang.org/ ?

```ruby
IO.binwrite "t.csv", ("a" * 100 + "\r\n") * 100
File.open("t.csv", encoding: "BOM|UTF-8", universal_newline: false) do |input|
  p input.gets(nil, 32 * 1024) # => "a...a\n...\na...a\r\n...\r\n"
end
```
