### ISSUE TITLE
CSV.parse behaves differently in Linux and in MacOS

### ISSUE THREAD

**Issue by gjaldon** [ruby/csv#191]
Given the following CSV file:

```csv
Year,Month,Fund ID,Department ID,Fund Name,Department Name,Amount
2012,12,1,10,General,Adm/Executive,155,319.95
```

Notice the last 2 columns of the 2nd line in the file. `319.95` is an extra column and `155` is under the `Amount` column. When doing `CSV.parse(file, headers: true)`, I get different output for MacOS and for Linux. 

In MacOS - the last column (`319.95`) is ignored (stored as a value under `nil` in the Table object)
In Linux - the last column under `Amount` is `155,319.95`

Behavior should be the same on both OSes and it seems that the MacOS is the more correct behavior. I leave it to you to decide what is best though.

**Comment by kou** [comment]
Could you show the output of `ruby -v -rcsv -e 'p CSV::VERSION'` on both platforms?

**Comment by gjaldon** [comment]
Here's the output I got:

Linux:
```
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
"3.1.2"
```

MacOS:
```
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
"3.1.2"
```

**Comment by kou** [comment]
Could you try 3.1.7?

**Comment by gjaldon** [comment]
@kou this is no longer an issue in `3.1.7`. I'm getting the same behavior on MacOS and Linux. Will `3.1.7` be shipped in next stable version of Ruby?

**Comment by kou** [comment]
If you mean 3.0.0, it will ship the latest version.

**Comment by gjaldon** [comment]
@kou awesome! Thanks for the help 🙏

**Comment by gjaldon** [comment]
@kou could you reopen this issue? Further testing still gives me different behavior between Linux (heroku) and MacOS for `3.1.7`. Could you check if that is the case?

**Comment by kou** [comment]
Could you provide a standalone Ruby script that reproduces this case?

If I can reproduce by the script, I reopen this.
