### ISSUE TITLE
Parsing CSV files from ARGF stopped working correctly starting from Ruby 2.5

### ISSUE THREAD

**Issue by Fravadona** [ruby/csv#228]
Hi everyone,

I noticed that, starting from Ruby 2.5, parsing multiple CSV files from ARGF stops after reading the first input.
For example, the simple one-liner:
``` sh
ruby -r csv -e 'CSV.new(ARGF).each{|row| p row}' file1.csv file2.csv
```
Only processes the content of file1.csv

**Comment by kou** [comment]
Thanks for your report.
I've fixed this.

**Comment by Fravadona** [comment]
Thank you. I applied the modification to my target Ruby 2.7 and it works now.
