### ISSUE TITLE
CSV::Table#headers returns [:"", :""] when  header is Japanese

### ISSUE THREAD

**Issue by taki** [ruby/csv#237]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require 'csv'

header = %w[都道府県 桃の生産量]
rows = [['山梨県', '37,600トン'], ['福島県', '22,500トン'], ['長野県', '12,100トン']]

CSV.open('momo.csv', 'w') do |csv|
  csv << header
  rows.map { |row| csv << row }
end

csv_table = CSV.table('momo.csv')

pp csv_table.headers
```

### Expected behavior

`csv_table#headers` returns `[:都道府県, :桃の生産量]`

### Actual behavior

`csv_table#headers` returns `[:"", :""]`

### System configuration
**Ruby version**: ruby 3.1.0p0
**csv version**: csv (default: 3.2.2)

**Comment by kou** [comment]
I understand your expected behavior but we can't change the current behavior to keep compatibility.

Could you specify `header_converters:` explicitly?

```ruby
csv_table = CSV.table('momo.csv', header_converters: lambda {|h| h.to_sym})
```

**Comment by kou** [comment]
We can provide `:symbol_raw` default header converter by adding a converter to `CSV::HeaderConverters`. If we provide `:symbol_raw`, we can write like the following:

```ruby
csv_table = CSV.table('momo.csv', header_converters: :symbol_raw)
```

@ericgpks Do you want to work on this?

**Comment by ericgpks** [comment]
@kou 
I would like to try to resolve this one! Thanks a lot!!

**Comment by kou** [comment]
@ericgpks Sure. Go ahead!

**Comment by kou** [comment]
Done by #239.

**Comment by taki** [comment]
Thank you!!
