### ISSUE TITLE
#eof? method returning wrong value when it's used on a csv file

### ISSUE THREAD

**Issue by Jee-El** [ruby/csv#258]
Ruby version : 3.1.2p20, as well as 2.7.4p191 (replit)
Steps to reproduce the issue(?) :
- Open a csv file with `CSV.open('file.csv')`
- Call `#pos` on it, it returns 0
- Call `#eof?` on it, it returns false
- Call `#read` on it
- Call `#pos` on it, it returns the last position
- Call `#eof?` on it, it returns false when it should be true

It seems to return true if `#eof?` isn't called before reading the file. (i.e: omit the third line above)

Demonstration : https://replit.com/@Jee-El/Ruby-CSV-eof-issue?v=1

**Comment by kou** [comment]
Could you paste `main.rb` and attach `event_attendees.csv` here for easy to refer?

**Comment by Jee-El** [comment]
`main.rb`
```
require 'csv'

# it returns true on the second call of #eof? as expected only if
# I comment the 4th line, starting from the line below this
puts 'csv'
csv = CSV.open('event_attendees.csv')
puts "pos : #{csv.pos}" # expecting 0
puts "eof? : #{csv.eof?}" # expecting false
csv.read
puts "pos : #{csv.pos}" # expecting 1814
puts "eof? : #{csv.eof?}" # expecting true
puts

# no issue when using File.open
puts 'File'
file = File.open('event_attendees.csv')
puts "pos : #{file.pos}" # expecting 0
puts "eof? : #{file.eof?}" # expecting false
file.read
puts "pos : #{file.pos}" # expecting 1814
puts "eof? : #{file.eof?}" # expecting true
```
[event_attendees.csv](https://github.com/ruby/csv/files/9482619/event_attendees.csv)

**Comment by kou** [comment]
Thanks. I've fixed this.
