### ISSUE TITLE
When a line contains an illegal character in a given encoding, throw something else than ArgurmentError

### ISSUE THREAD

**Issue by deepj** [ruby/csv#26]
This is one of the most confusing exception in the stdlib

I'd expect something like `CSV::MalformedCSVError` but `ArgumentError`. I have to use something like this in our code, where I could be sure I don't catch something else than only an illegal character on a given line:

```ruby
loop do
  row = csv.gets
  break unless row
  ...
rescue ArgumentError => exception
  raise if exception.message != 'invalid byte sequence in UTF-8'
  ...
end
```

**Comment by esparta** [comment]
Can you provide a sample csv file/string with this in order to reproduce the issue?

**Comment by deepj** [comment]
@esparta you can find an example here https://github.com/ruby/csv/issues/25

**Comment by kou** [comment]
Can you show a runnable Ruby script to reproduce this case?

**Comment by deepj** [comment]
@kou here https://github.com/ruby/csv/issues/25#issuecomment-368341779

**Comment by kou** [comment]
I've changed to `CSV::MalformedError` from `ArgumentError` for invalid encoding.

**Comment by golddranks** [comment]
Note that this is a breaking change for code that guards against invalid encodings by catching `ArgumentError`!

**Comment by kou** [comment]
Good catch.
Could you show a script that hits the incompatibility?

**Comment by kou** [comment]
(I want to know a real word example.)

**Comment by golddranks** [comment]
Sorry, I am not aware of a publicly available one. We (an internal code base) at my company were broken by this change upon migration to Ruby 2.6, but fortunately we found the bug because of a test case broke. It's easy to fix by adding a guard for the new error type, but it would benefit a greater visibility in the changelog.

**Comment by kou** [comment]
OK. Could you create a pull request that add a description for this into `NEWS.md`?
