### ISSUE TITLE
New release for Ruby 3.2

### ISSUE THREAD

**Issue by hsbt** [ruby/csv#268]
@kou 

👋 Can you cut the release from master or development branch for the Ruby 3.2 release? We have a plan to 3.2.0-rc1 at 12/5 or 12/6 and the final release at 12/25.

We synced the master branch of csv, fiddle, rexml, rss, stringio and strscan. They're also not released version. Can you also handle them? Thanks.

**Comment by hsbt** [comment]
Ah, `rexml` is already bundled gems. It's unnecessary to release at this time.

**Comment by kou** [comment]
OK. I'll do it. It may not be finished for 3.2.0-rc1 but must be finished for 3.2.0.

**Comment by kou** [comment]
csv: Done.

**Comment by kou** [comment]
stringio: Done but we may need to release one more version: https://github.com/ruby/stringio/pull/26

**Comment by kou** [comment]
strscan: Done.

**Comment by hsbt** [comment]
@kou Thanks! I'll organize them for Ruby 3.2 at https://github.com/ruby/ruby/pull/6890
