### ISSUE TITLE
feature: add option to limit length of strings

### ISSUE THREAD

**Issue by foonlyboy** [ruby/csv#271]
Hi at the ruby csv
I'd like to suggest a new feature.

There should be an option to limit the length of the strings generated as fields.

The prime use of generating csv is, to export data to customers,
for them to import that into Excel or LibreOffice.
That apps do have a limited cell size.
With LibreOffice that is 2^31-1

I'd like to suggest,
to add an option to CSV#generate
to ease to stay within the limits.

My idea would be to add a new option to limit the column length.

let's call that option :limit_column_size for a start:
- limit_column_size: true
- limit_column_size: Number
- limit_column_size: Proc(key, value)
- limit_column_size: :raise

one might also think about another way to express that:
compatible: :LibreOffice

**Comment by kou** [comment]
How about using the `write_converters:` option?
https://ruby.github.io/csv/doc/csv/recipes/generating_rdoc.html#label-Converting+Fields

**Comment by foonlyboy** [comment]
Hi Sutuo,
sorry for me asking.

**Comment by kou** [comment]
No problem.
