### ISSUE TITLE
CSV gem  for ruby which is less than ruby <2.5 version

### ISSUE THREAD

**Issue by ruby-shahid** [ruby/csv#29]
Hey friends I am unable to use this gem for any of the ruby-version which is less than 2.5.  I tried with all version of csv gem but still same issue. 
 The snippet below shows for least version of csv.
> Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    csv (~> 0.0.1) was resolved to 0.0.1, which depends on
      ruby (>= 2.5.0dev)

**Comment by kou** [comment]
What is your Ruby version?

**Comment by ruby-shahid** [comment]
@kou My Ruby Version is 2.3.1

**Comment by kou** [comment]
You can use csv gem with Ruby 2.3 since the next version.
