### ISSUE TITLE
Read StringIO with foreach

### ISSUE THREAD

**Issue by MarcPer** [ruby/csv#300]
## Proposal

I'd like to propose being able to open a `StringIO` `s` with `CSV.foreach(s)`, just as it's possible to open a file with `CSV.foreach(path)`.

I can investigate and open a PR if this behavior is desired.

## Current behavior
The documentation already says it should be possible to pass an IO object to `foreach`, but if an instance of `StringIO` is passed, we get:
```
no implicit conversion of StringIO into String (TypeError)
```

**Comment by kou** [comment]
If `CSV.foeach(io)` works, `CSV.foreach(string_io)` should work too.

**Comment by MarcPer** [comment]
Great, I'll open a PR with proposed changes in the next days.
