### ISSUE TITLE
compatibility with parallel

### ISSUE THREAD

**Issue by dorianmariecom** [ruby/csv#315]
```ruby
>> require 'csv'; require 'parallel'; CSV.generate { |csv| Parallel.each([1, 2, 3]) { |element| csv << [element] } }
=> ""
```

expected: outputs 1, 2, 3 as separate lines

actual: outputs nothing

**Comment by dorianmariecom** [comment]
works with threads, not with processes

**Comment by kou** [comment]
The parent process can't know what children processes did without you do.
See also: https://github.com/grosser/parallel/issues/352
