### ISSUE TITLE
3.3.1 parsing bug

### ISSUE THREAD

**Issue by stoodfarback** [ruby/csv#324]
I've compacted the data as much as I could to have a small script to reproduce. It appears to happen when there's a quoted comma in a cell and a blank row after.
```
csv_data = <<~HEREDOC
  "one,"
  
  "three"
HEREDOC

pp(CSV.parse(csv_data))
```

#### output with csv gem 3.3.0
```
[["one,"], [], ["three"]]
```

#### output with csv gem 3.3.1
```
[["one,"], ["three"], ["three"]]
```

#### system info
```
> ruby -v
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]
```

**Comment by kou** [comment]
Thanks for your report. I'll release a new version.

FYI: @marshall-lee GH-312 introduced this.

**Comment by stoodfarback** [comment]
Verified 3.3.2 fixes the bug for me.
Thank you for the fast update!
