### ISSUE TITLE
CSV.parse not removing BOM character

### ISSUE THREAD

**Issue by davich** [ruby/csv#43]
It looks like there's a bug in CSV 3.0.0 where `parse` with encoding 'bom|utf-8' doesn't remove the bom character (but it seems to be fine on the `read` method)

```
require 'csv'
require 'tempfile'
t = Tempfile.new("file.csv")
bom_character = 65_279
t << "name\nMy CSV".codepoints.unshift(bom_character).pack("U*")
t.rewind
csv = CSV.read(t, headers: true, encoding: 'bom|utf-8')
csv.first["name"]
=> "My CSV"
csv = CSV.parse(File.read(t), headers: true, encoding: 'bom|utf-8')
csv.first["name"]
=> nil
```

**Comment by kou** [comment]
BOM is for file not string data.

I don't know why some users want to use BOM for string data.
Can you show your use case?

**Comment by davich** [comment]
Right. So I should do:
```
csv = CSV.parse(File.read(t, encoding: 'bom|utf-8'), headers: true)
```

Thanks very much for your help! Sorry to raise an issue when the issue is with my understanding 👍

**Comment by matschaffer** [comment]
I had to do this with a file today as well (parsing an export from 新生銀行) 

`CSV.foreach(file, encoding: 'bom|utf-8')` - thanks for posting your solution @davich

**Comment by adamreisnz** [comment]
If you are rendering CSV output in an API response for download to the user, and you want the CSV to include a BOM marker (to prevent character encoding issues when opening the file in older versions of Excel), then it makes perfect sense for the output to have a UTF-8 BOM marker.

So stripping it from the body in tests seems like the way to go.

**Comment by kou** [comment]
If a response body is for download (`Content-Disposition: attachment`), a test should save the response to a file and read it as a file. A test should not parse the response body as a string (with `delete_prefix(BOM)`).
