### ISSUE TITLE
Converters doesn't work on generate_line

### ISSUE THREAD

**Issue by paniko0** [ruby/csv#46]
When you call

```ruby
CSV.generate_line(['a'], converters: lambda { |field| field.prepend '=' } )
``` 

doesn't do anything.

Checking the code, and correct me if I'm wrong, the only supported options when using `generate_line` are https://github.com/ruby/csv/blob/9ccdfe368c4446f8925daeca7d12d76d9855e445/lib/csv.rb#L1083

The "problem" in my opinion is that the documentation says that it can be used any option `new` understands: https://github.com/ruby/csv/blob/9ccdfe368c4446f8925daeca7d12d76d9855e445/lib/csv.rb#L563-L567

I can try to make changes to make it work if you guys point me what should be the expected behaviour.

**Comment by kou** [comment]
`:converters` option is for reading CSV data not for writing CSV data.
Can you show your use case for using converters on wiring CSV data?

**Comment by paniko0** [comment]
Basically because of a this [CVE](https://seclists.org/bugtraq/2014/Aug/115)

We are using ActiveAdmin and it uses `generate_line` to generate CSVs. We basically want to add an apostrophe in the beggining of the line if it starts with an `=` sign. (Basically samething as mentioned [here](https://github.com/activeadmin/activeadmin/issues/4256#issuecomment-168233711)). We didn't monkey-patch it because in Ruby's CSV docs we saw:

> generate_line(row, options = Hash.new) click to toggle source
...
**The options parameter can be anything ::new understands.**
...

Perhaps the doc should be changed?

Cheers

**Comment by esparta** [comment]
As @kou comments, the converters are for reading, not writing, and yes, perhaps the doc need to be more specific. More than 'anything than ::new understand' should be something like 'anything that ::new understands and applies'.

> Checking the code, and correct me if I'm wrong, the only supported options when using generate_line are

In this case are more than only `:colsep`, `:rowsep` and `:quote`:

```ruby
v = ["'a'", 'b']
headers = %w(first second)
l1 = CSV.generate_line(v, row_sep: '.', col_sep: '~', quote_char: '!',
                       force_quotes: true, write_headers: true, headers: headers, 
                       encoding: 'EUC-JP')
 => "!first!~!second!.!'a'!~!b!."
l1.encoding
 => #<Encoding:EUC-JP>
```

**Comment by kou** [comment]
@paniko0 Thanks for describing your use case. It makes sense.

We can't reuse `:converters` for this use case because it's for CSV -> Ruby. We need Ruby -> CSV for this use case.

It's OK to me that we add `:write_converters` for this use case.

**Comment by kou** [comment]
@esparta Thanks for your follow-up comment.
We can't reuse existing options for this use case because we need to care each data for this use case.
