### ISSUE TITLE
Proposal: Test coverage report for the project

### ISSUE THREAD

**Issue by esparta** [ruby/csv#49]
Currently the project has no test coverage report, this can be a nice to have to maintain and improve the CSV gem.

Pros:
- We can actively monitor what needs to be done on the current tests and be prepared also for the new contributions.
- Analyze new areas of improvements (on test and the code)

Cons:
- None. Not technical at least.

Plan (if accepted):

- [ ] Add [SimpleCov][simplecov] gem as development dependency and configure the unit test according.
- [ ] Optionally, setup a service to have the info visible(as [CodeClimate][codeclimate])

[simplecov]: https://github.com/colszowka/simplecov
[codeclimate]: https://codeclimate.com

**Comment by kou** [comment]
OK.

**Comment by kou** [comment]
@hsbt Can you enable this repository on Code Climate or Codecov? (I don't have any opinion for code coverage report service.)

**Comment by esparta** [comment]
The next step should be just a simple PR with all the changes, we can use Github's suggestions to change the CodeClimate Test ID and the URL for the Badge.
