### ISSUE TITLE
Add an option to remove spaces around column separator

### ISSUE THREAD

**Issue by kou** [ruby/csv#58]
For example:

```ruby
require "csv"
p CSV.parse('1, 2,3 , 4 ,5', remove_spaces_around_column_separator: true) # Needs shorter name
# [["1", "2", "3", "4", "5"]]
```

**Comment by geraldb** [comment]
> remove_spaces_around_column_separator: true   # Needs shorter name

FYI:  A great candidiates for a short names might be:

- trim: true     # or ltrim and rtrim

PS: In CSV values can be quoted e.g.:

     %Q{"1", "2","3" , "4" ,"5"} 

and in this case the "inner" spaces in quotes should get preserved and only the "outer" spaces trimmed / removed e.g.

     p CSV.parse( %Q{" 1 ", " 2 "," 3 " , " 4 " ," 5 "}, trim: true ) 
     # [[" 1 ", " 2 ", " 3 ", " 4 ", " 5 "]]

PS: By the way, I'm working on a "better" CSV reader for ruby (see <https://github.com/csvreader/csvreader>). Welcome to the wonder of CSV variants / formats / dialects. Keep up your great work. Cheers. Prost.

**Comment by kou** [comment]
Thanks.
I'm not sure whether "trim" naming is suitable for this case or not. But "strip" will be better than "trim". Because `String` uses `strip`.

**Comment by kou** [comment]
Implemented.
