### ISSUE TITLE
`CSV.parse('', headers: true)` was broken?

### ISSUE THREAD

**Issue by Watson1978** [ruby/csv#64]
If `headers: true` option was given, `CSV.parse()` returns `CSV::Table` object even if empty string will be passed as argument with Ruby 2.5.0.

However, in Ruby 2.6, the above behavior was incomatible. 

I want to know whether it is expected. Thank you!!

### Ruby 2.6

```
$ ruby -v ttt.rb
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
[]
Traceback (most recent call last):
ttt.rb:4:in `<main>': undefined method `headers' for []:Array (NoMethodError)
```

### Ruby 2.5

```
$ ruby -v ttt.rb
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
#<CSV::Table mode:col_or_row row_count:1>
[]
```

### Test code
```ruby
require 'csv'
row = CSV.parse('', headers: true)
p row
p row.headers
```

**Comment by kou** [comment]
It's unexpected.
We should fix it.
