### ISSUE TITLE
Reporting TODO MalformedCSVError with col_sep of multiple spaces in Ruby 2.6.0

### ISSUE THREAD

**Issue by thegorgon** [ruby/csv#67]
I'm experiencing a regression in the CSV library on upgrading to ruby 2.6.0:

Consider:

```
require 'csv'
CSV.parse("John Doe    Male\nJane Doe    Female", col_sep: "    ")
```

In ruby 2.5.1, this returns:

```
=> [["John Doe", "Male"], ["Jane Doe", "Female"]]
```

In ruby 2.6.0, this raises an exception (with a TODO in the message?)

```
CSV::MalformedCSVError (TODO: Meaningful message in line 1.)
```

**Comment by thegorgon** [comment]
I think fixing the issue will require more time than I can commit at the moment, but I can confirm that this was introduced in v3.0.2. I do not experience the same issue in v3.0.1.

**Comment by kou** [comment]
Thanks for your report.
I've fixed this.
