### ISSUE TITLE
Header refreshing problem of CSV::Table in v 3.0.3 

### ISSUE THREAD

**Issue by tkosaka1976** [ruby/csv#71]
Probably, v3.0.3, the header of CSV::Table is not refreshed by the addition of new CSV::Row object or Hash.

```ruby
require 'csv'

txt =<<TXT
"h1","h2","h3"
1,"test",3
2,"test",6
3,"test",9
TXT

table = CSV::parse(txt, headers: true)
table.each do |row|
  row << {"h4" => "additional"}
end
puts table.to_csv
```

# ver 3.0.3
>h1,h2,h3
>1,test,3,additional
>2,test,6,additional
>3,test,9,additional

# ver 3.0.0
>h1, h2,   h3, h4  
>1,  test, 3,  additional  
>2,  test, 6,  additional  
>3,  test, 9,  additional  

I'm not sure but from discussion in stack-overflow [board](https://stackoverflow.com/questions/54192058/how-to-refresh-the-headers-of-csvtable?noredirect=1#comment95216848_54192058) or my trial, it was started from 3.0.1.
v 3.0.0 is working as expect.

**Comment by anothermh** [comment]
My local testing showed the issue in 3.0.1, 3.0.2, and 3.0.3, but not in any prior versions.

**Comment by kou** [comment]
Thanks for your report.
I've fixed this. We should keep backward compatibility as much as possible.

**Comment by tkosaka1976** [comment]
Thank you @anothermh for your help.
Yes, I read your description.

But, I misunderstood that the version loaded from "require" is installed newest csv gem version.
Then, I updated csv gem to v3.0.4 but I still need to write:
`gem 'csv', '>=3.0.4'`
Probably, default csv gem still 3.0.1-3.0.3, right?

**Comment by kou** [comment]
This is a problem of Bundler: https://bugs.ruby-lang.org/issues/15469

**Comment by tkosaka1976** [comment]
> This is a problem of Bundler: https://bugs.ruby-lang.org/issues/15469
I see. I'll wait for the revision.

Thank you for your help.
