### ISSUE TITLE
CSV.parse(csv, headers: true) returns wrong value if CSV string has only one line

### ISSUE THREAD

**Issue by Watson1978** [ruby/csv#75]
When run following test code, Ruby 2.6.1's CSV library returns diffrenet result with Ruby 2.5.3.

## Test code
```ruby
require 'csv'

csv = <<-CSV
alice,有栖,ありす,,,,,,,,
CSV

rows = CSV.parse(csv, headers: true)
p rows.headers
```

## Ruby 2.6.1
```
$ ruby -v csv.rb
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]
["alice", "有栖", "ありす", nil, nil, nil, nil, nil, nil, nil, nil]
```

## Ruby 2.5.3
```
$ ruby -v csv.rb
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
[]
```

**Comment by kou** [comment]
Thanks for your report.
We've changed the behavior as a bug in CSV in Ruby 2.5.3. So this is an expected change.
See also #47.

BTW, what did you want to do with the behavior?

**Comment by Watson1978** [comment]
OK, I see. I can change test code in our product.
I just wanted to know whether this is right behavior.
