### ISSUE TITLE
#eof? doesn't reflect the actual object's state anymore for ruby >= 2.6

### ISSUE THREAD

**Issue by chiting** [ruby/csv#77]
Hello,

I'm creating this issue to know a bit more about the methods exposed from the CSV object that are delegated to the underlying IO object, including `#eof?`.

For ruby < 2.6, the behaviour was that whenever we call `#readline`, `#eof?` would return the state of the IO and tell if the end of file is reached. However, this behaviour has changed in ruby >= 2.6 and it seems that we cannot rely on `#eof?` anymore to tell the state of the IO when we want to readline on the CSV object.

Is it the intended behaviour? If so, shouldn't `#eof?` (and possibly other delegated methods from IO) be deprecated or at least a notice in the documentation that we shouldn't rely on it (them)?
If not, I'd be happy to give it a try and fix it.

Thanks

* ruby -v: `ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin16]`

For the following CSV test.csv file:
```
a,b,c,d
1,2,3,4
5,6,7,8
9,10,11,12
```

and the following code snippet:
``` ruby
require 'csv'
csv = ::CSV.open('./test.csv', {headers: true, col_sep: ','})
p csv.eof?
csv.readline
p csv.eof?
csv.readline
p csv.eof?
csv.readline
p csv.eof?

```

I got the following results with 2.6.1:
```
false
true
true
true
```

but using `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin16]` I got:
```
false
false
false
true
```

**Comment by kou** [comment]
Thanks for your report.
It's a bug. I've fixed this.
