### ISSUE TITLE
#read returns all rows instead of just the remaining ones

### ISSUE THREAD

**Issue by johvet** [ruby/csv#84]
Here's the documentation of the `#read` method:
> Slurps the remaining rows and returns an Array of Arrays.

Let's check this with the following sample script:

```ruby
# frozen_string_literal: true

require 'csv'

data = StringIO.new <<~DATA
  foo,1
  bar,2
  baz,3
DATA

csv = CSV.new(data)
puts "Shift 1: #{csv.shift.inspect}"
puts "Shift 2: #{csv.shift.inspect}"
puts "Rest   : #{csv.readlines.inspect}"
```

```bash
$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]

$ ruby sample-csv.rb 
Shift 1: ["foo", "1"]
Shift 2: ["bar", "2"]
Rest   : [["baz", "3"]]
```

Perfect - using ruby-2.5.3 this is all fine. 

Running this same example with ruby-2.6.2 it shows `#read` returns all rows of the file instead of just the remaining ones:

```bash
$ ruby -v
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]

$ ruby sample-csv.rb 
Shift 1: ["foo", "1"]
Shift 2: ["bar", "2"]
Rest   : [["foo", "1"], ["bar", "2"], ["baz", "3"]]
```

**Comment by kou** [comment]
It has been fixed at the latest release.
You can use the latest release with `gem install csv`.
I'll upgrade bundled csv in Ruby 2.6.3.
