### ISSUE TITLE
Handle =" as a designator for Excel 'formulas'

### ISSUE THREAD

**Issue by bmo** [ruby/csv#93]
We have a .CSV from a vendor that quotes numeric fields that should be treated as strings with =" -- for example (excerpt from a real file)

USD,="6161015399000000",54585234

I'm going to experiment with a custom converter. If that works, I'll close this issue.

**Comment by stevendaniels** [comment]
I agree that a custom converter would be the right approach to solving this problem. 

That being the case, should we close this issue?
