### ISSUE TITLE
CSV.parse(csv, col_sep: nil) throw a TypeError (no implicit conversion of nil into String) in ruby 2.6

### ISSUE THREAD

**Issue by beauraF** [ruby/csv#94]
Hi,

We tried to migrate one of our projects to ruby 2.6 and I am dealing with this difference in behavior that doesn't seem to be documented in changelogs.

_ruby 2.5.3_:

```ruby
irb(main):006:0> CSV.parse("toto,tata", col_sep: nil)
=> [["t", "o", "t", "o", ",", "t", "a", "t", "a", nil]]
```

_ruby 2.6.3_:

```ruby
irb(main):003:0> CSV.parse("toto,tata", col_sep: nil)
Traceback (most recent call last):
       15: from /Users/beauraf/.asdf/installs/ruby/2.6.3/bin/irb:23:in `<main>'
       14: from /Users/beauraf/.asdf/installs/ruby/2.6.3/bin/irb:23:in `load'
       13: from /Users/beauraf/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
       12: from (irb):3
       11: from /Users/beauraf/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/CSV.rb:685:in `parse'
       10: from /Users/beauraf/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/CSV.rb:1245:in `read'
        9: from /Users/beauraf/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/CSV.rb:1245:in `to_a'
        8: from /Users/beauraf/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/CSV.rb:1236:in `each'
        7: from /Users/beauraf/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/CSV.rb:1430:in `parser_enumerator'
        6: from /Users/beauraf/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/CSV.rb:1421:in `parser'
        5: from /Users/beauraf/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/CSV.rb:1421:in `new'
        4: from /Users/beauraf/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/csv/parser.rb:230:in `initialize'
        3: from /Users/beauraf/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/csv/parser.rb:328:in `prepare'
        2: from /Users/beauraf/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/csv/parser.rb:455:in `prepare_separators'
        1: from /Users/beauraf/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/csv/parser.rb:455:in `escape'
TypeError (no implicit conversion of nil into String)
```

Is this behaviour intended?

Thanks.

**Comment by kou** [comment]
It's not intended but could you show any useful use case for `col_sep: nil`?

**Comment by beauraF** [comment]
I don't have a particularly good example. But that the lib "crash" does not seem to me desirable. Go back to the previous behavior, or handle the `col_sep: nil` with an `ArgumentError` seems more better to me.

**Comment by kou** [comment]
OK.
We don't accept `nil` for `col_sep:`.

**Comment by crondaemon** [comment]
I have a use case for `col_sep: nil`, but I don't know if it is sound. I want to parse different sources, csv and flat files. I'm showing you a couple of examples. A csv file:

```
field1, field2
abc, def
```

and a flat file.

```
ghi
jk,l
```

The flat file includes the comma. To handle those 2 files (think not 2 files but tens of files csv and flat), I'd like to use the csv parser, passing `col_sep: nil` when reading the flat file. In this case `nil` would mean "I don't want a column separator". Is this a valid use case in your opinion?

**Comment by kou** [comment]
I think that `File.foreach("flat.txt", chomp: true) {|line| ...}` should be used for the flat file.
We should use the csv library only for a CSV (family) file. :-)

**Comment by crondaemon** [comment]
Yes, there are a bunch of methods to process a text file. However, a flat file can be considered a CSV with a single column and without an header. If you code is fed by both "real" csv and "semi" csv (flat files), the idea to have a single piece of code that handle them all could bo profitable.

**Comment by kou** [comment]
I don't want to recommend the "flat file is a CSV file" approach...
It will confuse many programmers...

**Comment by crondaemon** [comment]
I know, that was just to share a possible approach and to share some feedback.
