### ISSUE TITLE
CSV parser ignores the stream position of a StringIO

### ISSUE THREAD

**Issue by knu** [ruby/csv#99]
The CSV parser seems to call `@input.string` if `@input` is a StringIO, but I think it should check if `@input.pos` is zero before doing that.

```ruby
require 'csv'
require 'stringio'

strio = StringIO.new(<<'EOF')
aaa,b,c
EOF

p strio.read(2) #=> "aa"
p strio.pos #=> 2
p CSV.parse_line(strio) #=> ["aaa", "b", "c"] (["a", "b", "c"] is expected)
```

This problem was found by @katsyoshi and presented on ruby-jp.slack.com.  I tracked it down and identified the causing commit as eeab2ede, which was between v3.0.1 and v3.0.2.

**Comment by kou** [comment]
Thanks for your report.
This is duplicated: #98

**Comment by knu** [comment]
I only checked for the issues list and overlooked that.  Sorry!
